name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # cacheing
    - name: Cache local cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-local-bin-${{ hashFiles('book.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-local-bin-

    - name: Cache global cargo bin
      uses: actions/cache@v1
      with:
        path: /usr/share/rust/.cargo/bin
        key: ${{ runner.os }}-cargo-global-bin-${{ hashFiles('book.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-global-bin-

    - name: build
      run: scripts/build.sh

    - name: release
      run: |
        echo ${{ github.ref }}
      #if: github.ref == 'refs/heads/release'
      #run: |
      #  curl --request POST \
      #      --header 'authorization: Bearer ${{ secrets.USER_TOKEN }}' \
      #      --header "content-type: application/json" \
      #      --data '{
      #        "tag_name": "${{ tag",
      #      }'
      #      https:://api.github.com/repos/schell/fe_web_dev_in_rust/releases

      #  scripts/release.sh schell ${{ secrets.USER_TOKEN }}
