name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # cacheing
    - name: Cache local cargo bin
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-local-bin-${{ hashFiles('book.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-local-bin-

    - name: Cache global cargo bin
      uses: actions/cache@v1
      with:
        path: /usr/share/rust/.cargo/bin
        key: ${{ runner.os }}-cargo-global-bin-${{ hashFiles('book.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-global-bin-

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('web-sys-examples/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('web-sys-examples/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: web-sys-examples/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('web-sys-examples/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-target-

    - name: build
      run: scripts/build.sh

    - name: release
      if: endsWith(github.ref, 'master')
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        aws s3 sync book/ s3://preview.zyghost.com/guides/intro-to-rust-web/
        aws s3 sync book/ s3://zyghost.com/guides/intro-to-rust-web/
